# Generated by Django 3.2.8 on 2021-11-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiprojects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='p_type',
            new_name='type',
        ),
    ]
